import { Property } from "./types";

export const properties: Property[] = [
  {
    id: "1",
    title: "Residencial Luxo Moderno",
    type: "house",
    price: 2850000,
    location: {
      address: "Rua das Palmeiras, 450",
      city: "São Paulo",
      state: "SP",
      latitude: -16.46042,
      longitude: -54.59678,
    },
    features: {
      bedrooms: 4,
      bathrooms: 5,
      area: 450,
      parking: 3,
    },
    image: "/hero-property.jpg",
    gallery: ["/hero-property.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Casa de luxo com arquitetura moderna, amplos espaços e acabamento de primeira linha. Localizada em condomínio fechado com segurança 24h.",
    status: "available",
  },
  {
    id: "2",
    title: "Apartamento Vista Verde",
    type: "apartment",
    price: 890000,
    location: {
      address: "Av. das Nações, 1200",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      area: 120,
      parking: 2,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Apartamento moderno com vista para área verde, acabamento premium e localização privilegiada próximo a shopping e metrô.",
    status: "available",
  },
  {
    id: "3",
    title: "Cobertura Skyline Premium",
    type: "penthouse",
    price: 4200000,
    location: {
      address: "Av. Berrini, 3500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 5,
      bathrooms: 6,
      area: 380,
      parking: 4,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Cobertura de alto padrão com piscina privativa, terraço panorâmico e vista deslumbrante da cidade. Acabamento de luxo em todos os ambientes.",
    status: "available",
  },
  {
    id: "4",
    title: "Townhouse Contemporânea",
    type: "townhouse",
    price: 1650000,
    location: {
      address: "Rua dos Jardins, 890",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 4,
      area: 220,
      parking: 2,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Townhouse moderna em condomínio exclusivo, com design contemporâneo e jardim privativo. Perfeita para famílias que buscam conforto e segurança.",
    status: "available",
  },
  {
    id: "5",
    title: "Apartamento Gourmet",
    type: "apartment",
    price: 1280000,
    location: {
      address: "Rua Augusta, 2100",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 95,
      parking: 2,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Apartamento compacto com cozinha gourmet completa, ideal para quem aprecia gastronomia. Localização central com fácil acesso a restaurantes e cultura.",
    status: "available",
  },
  {
    id: "6",
    title: "Casa Condomínio Fechado",
    type: "house",
    price: 1950000,
    location: {
      address: "Alameda dos Anjos, 320",
      city: "Barueri",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
      parking: 3,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Casa espaçosa em condomínio fechado com área de lazer completa, incluindo piscina, quadra e salão de festas. Ambiente familiar e seguro.",
    status: "available",
  },
  {
    id: "7",
    title: "Loft Industrial Chic",
    type: "apartment",
    price: 720000,
    location: {
      address: "Rua da Consolação, 1500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 1,
      bathrooms: 1,
      area: 65,
      parking: 1,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Loft moderno com estilo industrial, pé-direito alto e conceito aberto. Perfeito para jovens profissionais que buscam praticidade e design.",
    status: "reserved",
  },
  {
    id: "8",
    title: "Duplex Vista Parque",
    type: "apartment",
    price: 1580000,
    location: {
      address: "Av. Ibirapuera, 2800",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 180,
      parking: 2,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Apartamento duplex com vista privilegiada para o parque, ambientes integrados e varanda gourmet. Lazer completo no condomínio.",
    status: "available",
  },
  {
    id: "9",
    title: "Apartamento Executivo Itaim",
    type: "apartment",
    price: 1450000,
    location: {
      address: "Av. Brigadeiro Faria Lima, 1500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 110,
      parking: 2,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Apartamento executivo no coração do Itaim, próximo a restaurantes e vida noturna. Acabamento premium com varanda gourmet.",
    status: "available",
  },
  {
    id: "10",
    title: "Casa Sobrado Vila Madalena",
    type: "house",
    price: 2200000,
    location: {
      address: "Rua Aspicuelta, 600",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 250,
      parking: 2,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Casa com arquitetura contemporânea na Vila Madalena, bairro boêmio e cultural. Jardim paisagístico e pátio interno.",
    status: "available",
  },
  {
    id: "11",
    title: "Cobertura Duplex Higienópolis",
    type: "penthouse",
    price: 3800000,
    location: {
      address: "Av. Higienópolis, 2000",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 4,
      area: 350,
      parking: 3,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Cobertura duplex em prédio histórico reformado, com piscina na cobertura e vista panorâmica. Localização nobre e requintada.",
    status: "available",
  },
  {
    id: "12",
    title: "Apartamento Compacto Vila Mariana",
    type: "apartment",
    price: 650000,
    location: {
      address: "Rua Vergueiro, 1800",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 1,
      bathrooms: 1,
      area: 55,
      parking: 1,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Apartamento compacto e funcional, ideal para investimento ou primeiro imóvel. Próximo ao metrô e comércios.",
    status: "available",
  },
  {
    id: "13",
    title: "Casa Condomínio Alphaville",
    type: "house",
    price: 2100000,
    location: {
      address: "Rua das Flores, 450",
      city: "Barueri",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      area: 300,
      parking: 3,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Casa em condomínio de luxo Alphaville com infraestrutura completa, segurança 24h e áreas de lazer premium.",
    status: "available",
  },
  {
    id: "14",
    title: "Townhouse Mooca",
    type: "townhouse",
    price: 1350000,
    location: {
      address: "Rua Correia de Melo, 800",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      area: 180,
      parking: 2,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Townhouse moderna na Mooca, bairro em desenvolvimento com ótima infraestrutura. Acabamento de qualidade e localização estratégica.",
    status: "available",
  },
  {
    id: "15",
    title: "Apartamento Luxo Pinheiros",
    type: "apartment",
    price: 2050000,
    location: {
      address: "Av. Pedroso de Morais, 1200",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 160,
      parking: 2,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Apartamento de luxo em Pinheiros, bairro sofisticado com vida noturna e gastronomia. Acabamento premium e varanda ampla.",
    status: "available",
  },
  {
    id: "16",
    title: "Loft Galpão Convertido Vila Leopoldina",
    type: "apartment",
    price: 980000,
    location: {
      address: "Rua Bandeira, 500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 1,
      area: 140,
      parking: 1,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Loft em galpão convertido, estilo industrial com pé-direito alto. Localização trendy em região em transformação.",
    status: "available",
  },
  {
    id: "17",
    title: "Cobertura Duplex Perdizes",
    type: "penthouse",
    price: 3200000,
    location: {
      address: "Rua Caiubi, 1000",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      area: 320,
      parking: 2,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Cobertura duplex em Perdizes, bairro residencial e tranquilo. Terraço panorâmico e acabamento sofisticado.",
    status: "sold",
  },
  {
    id: "18",
    title: "Casa Jardim Paulista",
    type: "house",
    price: 3500000,
    location: {
      address: "Rua Oscar Freire, 1500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 5,
      bathrooms: 4,
      area: 400,
      parking: 4,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Casa de alto padrão em Jardim Paulista, bairro nobre. Arquitetura clássica, jardim paisagístico e piscina.",
    status: "available",
  },
  {
    id: "19",
    title: "Apartamento Consolação",
    type: "apartment",
    price: 1100000,
    location: {
      address: "Av. Consolação, 2500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 100,
      parking: 1,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Apartamento moderno na Consolação, centro expandido com fácil acesso a tudo. Reformado com acabamento contemporâneo.",
    status: "available",
  },
  {
    id: "20",
    title: "Townhouse Tatuapé",
    type: "townhouse",
    price: 1200000,
    location: {
      address: "Rua Tuiuti, 800",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      area: 160,
      parking: 2,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Townhouse no Tatuapé, bairro residencial com boa infraestrutura. Acabamento moderno e localização privilegiada.",
    status: "available",
  },
  {
    id: "21",
    title: "Apartamento Studio Bela Vista",
    type: "apartment",
    price: 550000,
    location: {
      address: "Rua Marquês de Itu, 1200",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 1,
      bathrooms: 1,
      area: 45,
      parking: 0,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Apartamento studio na Bela Vista, centro de São Paulo. Ideal para jovens profissionais, próximo a metrô e comércios.",
    status: "available",
  },
  {
    id: "22",
    title: "Casa Condomínio Tamboré",
    type: "house",
    price: 2300000,
    location: {
      address: "Rua das Acácias, 300",
      city: "Santana de Parnaíba",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      area: 320,
      parking: 3,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Casa em condomínio de luxo Tamboré, com infraestrutura completa e segurança 24h. Ambiente familiar e tranquilo.",
    status: "available",
  },
  {
    id: "23",
    title: "Cobertura Duplex Vila Olímpia",
    type: "penthouse",
    price: 4500000,
    location: {
      address: "Av. Brigadeiro Faria Lima, 3000",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 5,
      bathrooms: 5,
      area: 400,
      parking: 4,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Cobertura duplex em Vila Olímpia, região corporativa de São Paulo. Piscina privativa e vista espetacular da cidade.",
    status: "reserved",
  },
  {
    id: "24",
    title: "Apartamento Aclimação",
    type: "apartment",
    price: 1000000,
    location: {
      address: "Rua Dona Margarida, 1000",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 95,
      parking: 1,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Apartamento na Aclimação, bairro residencial e arborizado. Próximo ao parque e com boa infraestrutura de comércios.",
    status: "available",
  },
  {
    id: "25",
    title: "Casa Brooklin",
    type: "house",
    price: 2600000,
    location: {
      address: "Rua Bandeira de Melo, 1500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 4,
      bathrooms: 4,
      area: 350,
      parking: 3,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Casa moderna no Brooklin, bairro sofisticado com excelente infraestrutura. Arquitetura contemporânea e acabamento premium.",
    status: "available",
  },
  {
    id: "26",
    title: "Townhouse Saúde",
    type: "townhouse",
    price: 1400000,
    location: {
      address: "Rua Afonso Braz, 600",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 200,
      parking: 2,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Townhouse na Saúde, bairro em desenvolvimento. Acabamento moderno, varanda e localização estratégica.",
    status: "available",
  },
  {
    id: "27",
    title: "Apartamento Duplex Cambuci",
    type: "apartment",
    price: 750000,
    location: {
      address: "Rua Tamandaré, 1000",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 2,
      bathrooms: 1,
      area: 85,
      parking: 1,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Apartamento duplex no Cambuci, bairro histórico em revitalização. Ótimo custo-benefício e localização central.",
    status: "available",
  },
  {
    id: "28",
    title: "Cobertura Duplex Liberdade",
    type: "penthouse",
    price: 2800000,
    location: {
      address: "Rua Galvão Bueno, 1500",
      city: "São Paulo",
      state: "SP",
      latitude: -23.5505,
      longitude: -46.6333,
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 280,
      parking: 2,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Cobertura duplex na Liberdade, bairro multicultural e vibrante. Terraço com vista e acabamento sofisticado.",
    status: "available",
  },
];
