import { Property } from "./types";

export const properties: Property[] = [
  {
    id: "1",
    title: "Residencial Luxo Moderno",
    type: "house",
    price: 2850000,
    location: {
      address: "Rua das Palmeiras, 450",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 4,
      bathrooms: 5,
      area: 450,
      parking: 3,
    },
    image: "/hero-property.jpg",
    gallery: ["/hero-property.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Casa de luxo com arquitetura moderna, amplos espaços e acabamento de primeira linha. Localizada em condomínio fechado com segurança 24h.",
    status: "available",
  },
  {
    id: "2",
    title: "Apartamento Vista Verde",
    type: "apartment",
    price: 890000,
    location: {
      address: "Av. das Nações, 1200",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      area: 120,
      parking: 2,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Apartamento moderno com vista para área verde, acabamento premium e localização privilegiada próximo a shopping e metrô.",
    status: "available",
  },
  {
    id: "3",
    title: "Cobertura Skyline Premium",
    type: "penthouse",
    price: 4200000,
    location: {
      address: "Av. Berrini, 3500",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 5,
      bathrooms: 6,
      area: 380,
      parking: 4,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Cobertura de alto padrão com piscina privativa, terraço panorâmico e vista deslumbrante da cidade. Acabamento de luxo em todos os ambientes.",
    status: "available",
  },
  {
    id: "4",
    title: "Townhouse Contemporânea",
    type: "townhouse",
    price: 1650000,
    location: {
      address: "Rua dos Jardins, 890",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 3,
      bathrooms: 4,
      area: 220,
      parking: 2,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Townhouse moderna em condomínio exclusivo, com design contemporâneo e jardim privativo. Perfeita para famílias que buscam conforto e segurança.",
    status: "available",
  },
  {
    id: "5",
    title: "Apartamento Gourmet",
    type: "apartment",
    price: 1280000,
    location: {
      address: "Rua Augusta, 2100",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 95,
      parking: 2,
    },
    image: "/property-4.jpg",
    gallery: ["/property-4.jpg", "/property-1.jpg", "/property-2.jpg", "/property-3.jpg"],
    description: "Apartamento compacto com cozinha gourmet completa, ideal para quem aprecia gastronomia. Localização central com fácil acesso a restaurantes e cultura.",
    status: "available",
  },
  {
    id: "6",
    title: "Casa Condomínio Fechado",
    type: "house",
    price: 1950000,
    location: {
      address: "Alameda dos Anjos, 320",
      city: "Barueri",
      state: "SP",
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
      parking: 3,
    },
    image: "/property-1.jpg",
    gallery: ["/property-1.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg"],
    description: "Casa espaçosa em condomínio fechado com área de lazer completa, incluindo piscina, quadra e salão de festas. Ambiente familiar e seguro.",
    status: "available",
  },
  {
    id: "7",
    title: "Loft Industrial Chic",
    type: "apartment",
    price: 720000,
    location: {
      address: "Rua da Consolação, 1500",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 1,
      bathrooms: 1,
      area: 65,
      parking: 1,
    },
    image: "/property-2.jpg",
    gallery: ["/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/hero-property.jpg"],
    description: "Loft moderno com estilo industrial, pé-direito alto e conceito aberto. Perfeito para jovens profissionais que buscam praticidade e design.",
    status: "reserved",
  },
  {
    id: "8",
    title: "Duplex Vista Parque",
    type: "apartment",
    price: 1580000,
    location: {
      address: "Av. Ibirapuera, 2800",
      city: "São Paulo",
      state: "SP",
    },
    features: {
      bedrooms: 3,
      bathrooms: 3,
      area: 180,
      parking: 2,
    },
    image: "/property-3.jpg",
    gallery: ["/property-3.jpg", "/property-4.jpg", "/property-1.jpg", "/property-2.jpg"],
    description: "Apartamento duplex com vista privilegiada para o parque, ambientes integrados e varanda gourmet. Lazer completo no condomínio.",
    status: "available",
  },
];
